name: CI (Check & Build)

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    name: Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Code Format Check
        run: pnpm format:check

      - name: Type & Component Check
        run: pnpm check

      - name: Build Test
        run: pnpm build
